version: "3"

services:
    mysql:
        image: mysql:latest
        ports:
            - "3308:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=clave123
            - MYSQL_DATABASE=agendabd
        volumes:
            - mysql_data:/var/lib/mysql

volumes:
    mysql_data:
# docker compose up
